version: 2.1

executors:
  golang:
    docker:
      - image: cimg/go:1.18.4

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make
      - run: ./workdir/one-git-version apply --path ./ --service app --access-token ${GITHUB_TOKEN}
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: ./workdir/
          paths:
            - ./one-git-version

  publish:
    executor: golang
    steps:
      - attach_workspace:
          at: ./workspace/
      - run:
          name: "Publish Release on GitHub"
          command: |
            go install github.com/tcnksm/ghr@latest
            VERSION=$(./workspace/one-git-version version)
            echo ${VERSION}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./workspace/

workflows:
  version: 2
  one-git-version:
    jobs:
      - build:
          context:
            - artifact-build-and-push
      - publish:
          context:
            - artifact-build-and-push
          requires:
            - build
          filters:
            branches:
              only:
                - main
